language: python
sudo: required
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
script: ./runtests.sh
addons:
  postgresql: "9.3"
before_script:
  - flake8 streamwebs_frontend/
  - psql -c "CREATE DATABASE streamwebs;" -U postgres
  - psql -U postgres -c "CREATE EXTENSION postgis;" streamwebs
