version: '2'
services:
  db:
    image: mdillon/postgis
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
