version: '2'
services:
  db:
    image: mdillon/postgis
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - .:/opt/streamwebs
    working_dir: /opt/streamwebs
    command: python /opt/streamwebs/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db
